#!/bin/sh

feeds() {
    feed 'Ars Technica' 'https://feeds.arstechnica.com/arstechnica/features'
    feed 'Bruce Schneier' 'https://www.schneier.com/feed/atom'
    feed 'Coda Hale' 'https://codahale.com/atom.xml'
    feed 'Daniel J. Bernstein' 'https://blog.cr.yp.to/feed.application=xml'
    feed 'Filippo Valsorda' 'https://words.filippo.io/rss/'
    feed 'Hiltjo Posthuma' 'http://codemadness.org/rss.xml'
    feed 'Keccak Team' 'https://keccak.team/news.atom'
    feed 'Lobsters' 'https://lobste.rs/rss'
    feed 'Loup Vaillant' 'https://loup-vaillant.fr/updates'
    feed 'Matthew Green' 'https://blog.cryptographyengineering.com/feed/'
    feed 'Nate Lawson' 'https://rdist.root.org/feed/'
    feed 'Monero' 'https://www.getmonero.org/feed.xml'
    feed 'Mullvad' 'https://mullvad.net/en/blog/feed/atom/'
    feed 'Raspberry Pi' 'https://www.raspberrypi.com/news/feed/'
    feed 'Tails' 'https://tails.boum.org/news/index.en.rss'
    feed 'Tor' 'https://blog.torproject.org/feed.xml'
    feed 'Wired' 'https://www.wired.com/feed/category/backchannel/latest/rss'
}

fetch() {
    /usr/bin/curl -fsLm 15 "$2" || exit 1
}
